apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment1
  namespace: default
spec:
  template :
    spec:
      containers:
        - name: the-container
          image: <+serviceConfig.serviceDefinition.spec.variables.image>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-deployment1
  namespace: default
spec:
  replicas: <+serviceConfig.serviceDefinition.spec.variables.replica>
