# K8S Deployments example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+stage.variables.appName>-deployment
  labels:
    app: <+stage.variables.appName>
    type: front-end
spec:
  template:
    metadata:
      name: <+stage.variables.appName>-pod
      labels:
        app: <+stage.variables.appName>
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 1
  selector:
    matchLabels:
      type: front-end