apiVersion: v1
kind: Service
metadata:
  name: <+stage.variables.appName>-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  selector:
    app: <+stage.variables.appName>
    type: front-end