pipeline:
  name: reconTest
  identifier: reconTest
  tags: {}
  template:
    templateRef: account.reconPipe
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s3
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s4
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s5
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s6
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s7
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s8
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s9
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
        - stage:
            identifier: s10
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - stepGroup:
                          identifier: ss
                          template:
                            templateInputs:
                              steps:
                                - step:
                                    identifier: ss
                                    template:
                                      templateInputs:
                                        type: ShellScript
                                        timeout: <+input>
  projectIdentifier: DoNotDelete_AR7
  orgIdentifier: default
