pipeline:
  name: reconTest
  identifier: reconTest
  tags: {}
  template:
    templateRef: account.reconPipe
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - step:
                          identifier: ss
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - step:
                          identifier: sss
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
        - stage:
            identifier: s3
            template:
              templateInputs:
                type: Deployment
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    serviceOverrideInputs: <+input>
                    infrastructureDefinitions: <+input>
                  service:
                    serviceRef: <+input>
                    serviceInputs: <+input>
                  execution:
                    steps:
                      - step:
                          identifier: ss
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
  projectIdentifier: DoNotDelete_AR7
  orgIdentifier: default
