pipeline:
  name: Repo2-main-CD-pipe
  identifier: Repo2mainCDpipe
  projectIdentifier: DoNotDelete_ElasticBugBash
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs1
        identifier: cs1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10s
        tags: {}
