pipeline:
  name: rohan
  identifier: rohan
  projectIdentifier: GitEx
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy
        identifier: Deploy
        template:
          templateRef: Deploy
          versionLabel: "1.1"
          gitBranch: naman-test
          templateInputs:
            type: Deployment
            spec:
              service:
                serviceRef: <+input>
                serviceInputs: <+input>
              environment:
                environmentRef: <+input>
                environmentInputs: <+input>
                serviceOverrideInputs: <+input>
                infrastructureDefinitions: <+input>
