{{- if .Values.env.config}}
apiVersion: v1
metadata:
  name: hehehereleasee
kind: ConfigMap
data:
{{.Values.env.config | toYaml | indent 2}}
---
{{- end}}
# dasdsada
{{- if .Values.env.secrets}}
apiVersion: v1
metadata:
  name: hehehereleasee
kind: Secret
stringData:
{{.Values.env.secrets | toYaml | indent 2}}
---
{{- end}}
# aksdaskdjkasdnsak
# fasdsadad
{{- if .Values.dockercfg}}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    harness.io/skip-versioning: "true"
  name: {{.Values.name}}-dockercfg
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
{{- end}}
{{- if not (lookup "apps/v1" "Deployment" "tarun-ng" "randomtarra8" )}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "todolist.fullname" . }}
  labels:
    app: {{ template "todolist.name" . }}
    chart: {{ template "todolist.chart" . }}
    release: "{{ .Release.Name }}"
    harness.io/release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "todolist.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "todolist.name" . }}
        release: {{ .Release.Name }}
        harness.io/release: {{ .Release.Name }}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}
      containers:
        - name: todolist-harness
          image: registry.hub.docker.com/harness/todolist-sample:latest
        - name: {{ .Chart.Name }}
          image: {{.Values.image}}
          imagePullPolicy: {{ .Values.pullPolicy }}
          {{- if or .Values.env.config .Values.env.secrets}}
          envFrom:
          {{- if .Values.env.config}}
          - configMapRef:
              name: {{.Values.name}}
          {{- end}}
          {{- if .Values.env.secrets}}
          - secretRef:
              name: {{.Values.name}}  
          {{- end}}
          {{- end}}
---
{{- end }}
