{{- if not (lookup "v1" "Service" "tarun-ng" "testinghelmdeploy-todolist" )}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "todolist.fullname" . }}
  annotations:
    helm.sh/resource-policy: "keep"
  labels:
    app: {{ template "todolist.name" . }}
    chart: {{ template "todolist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 90
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "todolist.name" . }}
    release: {{ .Release.Name }}
---
{{- end}}
