{{- if not (lookup "networking.istio.io/v1alpha3" "ServiceEntry" "test" "test-service-entry") }}
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: test-service-entry
  namespace: test
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  hosts:
  - www.google.com # place any test host here
  ports:
  - number: 443
    name: https-port
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---
{{- end }}
