
service:
  type: ClusterIP
  port: 80

deployment:
    container:
      image: <+artifact.image>
      name: <+serviceVariables.serviceName>-container
      port: 80

global:
  appName: <+stage.variables.resourcePrefix>-<+serviceVariables.serviceName>