---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - webapp.harness.io
  resources:
  - samplek8s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.harness.io
  resources:
  - samplek8s/finalizers
  verbs:
  - update
- apiGroups:
  - webapp.harness.io
  resources:
  - samplek8s/status
  verbs:
  - get
  - patch
  - update
