apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.testValues.configMap | default .Release.Name }}
  labels:
    app: {{ .Release.Name }}
data:
  {{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.testValues.secret | default .Release.Name }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
