apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
  namespace: default
spec:
  template :
    spec:
      containers:
        - name: example-app
          image: ${serviceVariable.imageEnv}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deploy
spec:
  replicas: ${serviceVariable.replicaEnv}
