apiVersion: v1
kind: Service
metadata:
  name: {{.Values.namePrefix}}-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  selector:
    app: {{.Values.namePrefix}}-deployment