resources:
  - ../../application
namePrefix: dev-
configMapGenerator:
- name: example-config
  namespace: default
  #behavior: replace
  files:
    - configs/config.json
patchesStrategicMerge:
  - env.yaml