pipeline:
  name: K8s-1
  identifier: K8s1
  projectIdentifier: test
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: test3
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: env8
            deployToAll: false
            infrastructureDefinitions:
              - identifier: test
          execution:
            steps:
              - stepGroup:
                  name: stepGroup1
                  identifier: stepGroup1
                  steps:
                    - parallel:
                        - stepGroup:
                            name: stepGroup2
                            identifier: stepGroup2
                            steps:
                              - step:
                                  type: ShellScript
                                  name: step1
                                  identifier: step1
                                  spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                      type: Inline
                                      spec:
                                        script: |-
                                          echo hello
                                          echo "service name: "<+service.name>

                                          echo "service variables: "<+serviceVariables.stringVar> 
                                    environmentVariables: []
                                    outputVariables: []
                                  timeout: 10m
                        - step:
                            type: ShellScript
                            name: shell2
                            identifier: shell2
                            spec:
                              shell: Bash
                              onDelegate: true
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo hi
                                    echo "service name: "<+service.name>

                                    echo "service variables: "<+serviceVariables.stringVar> 
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
