apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: {{.Values.name}}-helm-crd-samples.{{.Values.group}}
spec:
  group: {{.Values.group}}
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              x-kubernetes-preserve-unknown-fields: true
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    kind: {{.Values.name}}-helm-crd-sample
    plural: {{.Values.name}}-helm-crd-samples