name: <+stage.variables.resourceNamePrefix>
replicas: <+stage.variables.replicas>

image: <+artifacts.primary.image>
dockercfg: <+artifacts.primary.imagePullSecret>

createNamespace: true
namespace: <+infra.namespace>

serviceType: ClusterIP

servicePort: 80
serviceTargetPort: 3000