# https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: {{.Values.name}}-dockercfg
  annotations:
    harness.io/skip-versioning: "true"
data:
  .dockercfg: {{.Values.dockercfg}}
type: kubernetes.io/dockercfg
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Values.name}}-daemonset
  namespace: {{.Values.namespace}}
  labels:
    k8s-app: {{.Values.name}}
spec:
  selector:
    matchLabels:
      name: {{.Values.name}}
  template:
    metadata:
      labels:
        name: {{.Values.name}}
    spec:
      tolerations:
        # these tolerations are to have the daemonset runnable on control plane nodes
        # remove them if your control plane nodes should not run pods
        #- key: node-role.kubernetes.io/control-plane
        #  operator: Exists
        #  effect: NoSchedule
        #- key: node-role.kubernetes.io/master
        #  operator: Exists
        #  effect: NoSchedule
      imagePullSecrets:
        - name: {{.Values.name}}-dockercfg
      containers:
        - name: {{.Values.name}}-container
          image: {{.Values.image}}
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log