# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.name}}-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{.Values.name}}