# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{.Values.name}}-persistentvolume
spec:
  storageClassName: "local"
  claimRef:
    name: {{.Values.name}}-persistentvolumeclaim
    namespace: {{.Values.namespace}}