# https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
apiVersion: v1
kind: Pod
metadata:
  name: {{.Values.name}}-pod
  labels:
    environment: production
    app: nginx
    podlabel: {{.Values.name}}-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80