name: marko-example
replicas: 1

image: <+artifact.image>
pullPolicy: Always
dockercfg: H@rne$$123

sidecar:
  image: <+artifacts.sidecars.markosidecar1.image>
  pullPolicy: Always
  dockercfg: H@rne$$123


createNamespace: false
namespace: <+infra.namespace>
