{{- if .Values.pdb.minAvailable}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.name}}-pdb
spec:
  invalidNonSpecField: someValue
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: {{.Values.name}}
  {{- end}}